import * as fs from "node:fs";
import * as path from "node:path";

import { loadWithImports } from "../js/index.js";
import { ONTOLOGY_CATALOG } from "../js/constants.js";
import { getLocalOntologyPath, LOCAL_ONTOLOGY_DIST_DIR } from "./helpers.js";
import {
  compareVowlSemantics,
  getFilePathKey,
  installLocalOntologyFetch,
  parseVowlJson,
  readJavaReferenceOutput,
} from "./vowlDifferential.js";

// Section 18.8 defines the corpus differential as Java OWL2VOWL reference output
// compared against WebVOWL output "through new architecture", and section 17.15
// makes production differential acceptance a Phase 8 gate. This suite is that
// gate and remains the executable comparison after Phase 18 retired the
// pre-cutover JavaScript pipeline.
// The entry point under test is `loadWithImports`, because that is what
// `src/app/js/loadingModule.js` calls for every document a user opens. Testing
// the plain entry instead would gate a path the application does not take.
//
// Phase 9 puts Turtle under this same semantic differential. Syntax support is
// gated separately; differences here are about OWL reconstruction and VOWL
// conversion after Turtle has produced the shared RDF/JS representation.

const TEST_TIMEOUT_MS = 60_000;
const REGISTER_URL = new URL(
  "../../../docs/owl2vowl/compatibility/production-corpus-differences.json",
  import.meta.url,
);

const excludedBaseFiles = new Set(["musicontology.rdfs"]);

const baseTargetFiles = Object.values(ONTOLOGY_CATALOG)
  .map(getLocalOntologyPath)
  .filter((file) => !excludedBaseFiles.has(path.basename(file)));

const extraTargetFiles = [
  path.join(LOCAL_ONTOLOGY_DIST_DIR, "iso", "31073", "ed-1", "20260626"),
  path.join(
    LOCAL_ONTOLOGY_DIST_DIR,
    "iso-iec",
    "11179",
    "-3",
    "ed-4",
    "20260714",
  ),
  path.join(LOCAL_ONTOLOGY_DIST_DIR, "universal", "reference-data", "20260714"),
  path.join(LOCAL_ONTOLOGY_DIST_DIR, "universal", "core", "20260714"),
  path.join(LOCAL_ONTOLOGY_DIST_DIR, "universal", "extended", "20260714"),
];

// Documents whose reference fixture was produced from a different import
// closure than this harness can serve. The pinned outputs were generated by
// running the jar against local files with whatever network access that run
// had, so a document's closure then and now can differ in either direction.
//
// The criterion is the set of namespaces each side emitted entities from: a
// namespace present on one side and wholly absent on the other means the two
// converted different ontologies, and every difference in such a document is
// then uninterpretable as an engine comparison. Pairing an import IRI to the
// namespace its entities land in proved unreliable - `dcat3.rdf` imports
// `prov-o#` while its entities appear under `prov` - so the namespace sets are
// compared directly instead.
//
// `prov.owl` is the starkest case: its fixture contains entity IRIs beginning
// `file:/C:/Users/...`, the generating machine's own path, which nothing this
// project produces can ever match.
//
// These are excluded rather than registered. A governed difference is a
// difference in conversion; this is a difference in input, and recording it as
// though the engines disagreed would be false. Regenerating the fixtures against
// this corpus removes the whole class and would let every one of these back in -
// tracked as a follow-up in `docs/owlapi-js/migration/migration-status.md`.
//
// Most cases are exposed by a namespace missing altogether. The three Turtle
// additions below make the other failure modes concrete: a version IRI absent
// from the catalog (`BenchmarkOntology.ttl`), modular imports absent from it
// (`ssn.ttl`), and a historical reference run that fetched a different
// serialization/version of the same namespace (`time-gregorian.ttl` and the
// two universal ontologies that transitively import it). The last is evidenced
// by imported `time:Year` differing between the `time-gregorian.ttl` Java
// fixture and the separately pinned `time.rdf` Java fixture before either is
// compared with JS.
// Regenerating every fixture against one pinned closure remains the real fix.
const divergentImportClosureFiles = new Set([
  "BenchmarkOntology.ttl",
  "Drammar_NunnaryScene_Optimized_Rules.owl",
  "dcat3.rdf",
  "dcterms.rdf",
  "doap.rdf",
  "prov.owl",
  "ssn.ttl",
  "tagont.owl",
  "time-gregorian.ttl",
  "universal_core_20260714",
  "universal_extended_20260714",
  "wgs84_pos.rdf",
]);

const targetFiles = [...new Set([...baseTargetFiles, ...extraTargetFiles])]
  .filter((file) => fs.existsSync(file))
  .filter((file) => !divergentImportClosureFiles.has(getFilePathKey(file)))
  .sort();

const register = JSON.parse(fs.readFileSync(REGISTER_URL, "utf8"));

const describeDifference = (keyName, failedChecks, detail) => {
  const sample = (values, limit = 5) =>
    values.length > limit
      ? `${values.slice(0, limit).join(", ")} (+${values.length - limit} more)`
      : values.join(", ");

  const lines = [
    `Unregistered production differences for "${keyName}".`,
    `Failed dimensions: ${failedChecks.join(", ")}`,
  ];

  if (
    !detail.iri.reference !== !detail.iri.candidate ||
    detail.iri.reference !== detail.iri.candidate
  ) {
    lines.push(
      `  iri: java=${detail.iri.reference} js=${detail.iri.candidate}`,
    );
  }
  if (detail.classes.referenceCount !== detail.classes.candidateCount) {
    lines.push(
      `  classes: java=${detail.classes.referenceCount} js=${detail.classes.candidateCount}` +
        ` missing=${detail.classes.missing.length} extra=${detail.classes.extra.length}`,
    );
    if (detail.classes.missing.length) {
      lines.push(`    missing: ${sample(detail.classes.missing)}`);
    }
    if (detail.classes.extra.length) {
      lines.push(`    extra: ${sample(detail.classes.extra)}`);
    }
  }
  for (const [name, group] of [
    ["properties", detail.properties],
    ["subclasses", detail.subclasses],
    ["disjoints", detail.disjoints],
  ]) {
    const missing = group.missing ?? [];
    const extra = group.extra ?? [];
    const structure = group.structureMismatches ?? [];
    if (missing.length || extra.length || structure.length) {
      lines.push(
        `  ${name}: missing=${missing.length} extra=${extra.length}` +
          (structure.length ? ` structure=${structure.length}` : ""),
      );
      if (missing.length) {
        lines.push(`    missing: ${sample(missing)}`);
      }
      if (extra.length) {
        lines.push(`    extra: ${sample(extra)}`);
      }
      if (structure.length) {
        lines.push(`    structure: ${sample(structure)}`);
      }
    }
  }
  if (
    detail.annotations.classes.length ||
    detail.annotations.properties.length
  ) {
    lines.push(
      `  annotations: classes=${detail.annotations.classes.length} properties=${detail.annotations.properties.length}`,
    );
    if (detail.annotations.classes.length) {
      lines.push(`    classes: ${sample(detail.annotations.classes)}`);
    }
    if (detail.annotations.properties.length) {
      lines.push(`    properties: ${sample(detail.annotations.properties)}`);
    }
  }
  if (detail.instances.length) {
    lines.push(`  instances: ${detail.instances.length} differing`);
  }
  for (const name of ["labels", "types", "attributes"]) {
    const group = detail[name];
    if (group.classes.length || group.properties.length) {
      lines.push(
        `  ${name}: classes=${group.classes.length} properties=${group.properties.length}`,
      );
      if (group.classes.length) {
        lines.push(`    classes: ${sample(group.classes)}`);
      }
      if (group.properties.length) {
        lines.push(`    properties: ${sample(group.properties)}`);
      }
    }
  }

  lines.push(
    "",
    "Every dimension must be justified separately. Add to",
    "docs/owl2vowl/compatibility/production-corpus-differences.json under",
    `documents["${keyName}"]:`,
    ...failedChecks.flatMap((name) => [
      `  "${name}": {`,
      '    "summary": "One line on what differs",',
      '    "justification": "Why the production path may differ from the oracle here",',
      '    "authority": "The specification or evidence relied on"',
      "  },",
    ]),
  );

  const error = new Error(lines.join("\n"));
  error.stack = lines.join("\n");
  throw error;
};

// Imports the reference run demonstrably did not have. The pinned outputs were
// produced by running the jar against local files, so an import it could not
// fetch is absent from the fixture; where this project's catalog resolves the
// same IRI, the two sides convert different ontologies and the difference says
// nothing about either engine.
//
// Each entry is evidenced the same way: the reference output contains no entity
// from that namespace which the importing document does not itself mention, and
// an entity the document never mentions can only have come from a resolved
// import. `http://www.mindswap.org/2003/owl/foaf` is a long-dead host, which is
// why `tagont.owl` alone accounted for 77 spurious extra properties.
//
// Withholding these aligns the closures. It does not touch production import
// resolution, which continues to serve users the fuller graph.
// Scoped per document, because availability was a property of each reference
// run rather than of the IRI. `http://purl.org/dc/terms` was plainly reachable
// when `cube.rdf` was generated and unreachable when `tagont.owl` was, so a
// single global list withholds it from documents that legitimately had it.
const UNAVAILABLE_TO_THE_REFERENCE_RUN = new Map([
  [
    "tagont.owl",
    ["http://www.mindswap.org/2003/owl/foaf", "http://purl.org/dc/terms"],
  ],
  ["ontology_v3.3.rdf", ["http://geovocab.org/spatial"]],
]);

describe("production entry corpus differential", () => {
  let restoreFetch;

  beforeAll(() => {
    restoreFetch = installLocalOntologyFetch();
  });

  afterAll(() => {
    restoreFetch();
  });

  test("the supported production corpus is present, including Turtle", () => {
    expect(targetFiles.length).toBeGreaterThan(0);
    expect(
      targetFiles.filter((file) => path.extname(file).toLowerCase() === ".ttl")
        .length,
    ).toBeGreaterThan(0);
  });

  for (const file of targetFiles) {
    const keyName = getFilePathKey(file);

    test(
      `matches the pinned oracle for ${keyName}`,
      async () => {
        const javaRaw = readJavaReferenceOutput(file);
        expect(javaRaw).not.toBeNull();

        const text = fs.readFileSync(file, "utf8");
        const withheld = UNAVAILABLE_TO_THE_REFERENCE_RUN.get(keyName);
        const restoreDocumentFetch = withheld
          ? installLocalOntologyFetch({ unavailableImports: withheld })
          : undefined;
        const jsRaw = withheld
          ? await loadWithImports(text, { fileName: keyName }).finally(
              restoreDocumentFetch,
            )
          : await loadWithImports(text, { fileName: keyName });
        expect(jsRaw).toBeDefined();

        const { isExactMatch, failedChecks, detail } = compareVowlSemantics(
          parseVowlJson(javaRaw),
          parseVowlJson(jsRaw),
        );

        const entry = register.documents[keyName] ?? {};
        const justified = Object.keys(entry);

        // A justification for a dimension that no longer differs is stale.
        // Failing on it forces the register to be cleaned up when a difference
        // is fixed, so it cannot accumulate explanations for behaviour the
        // engine no longer has.
        expect(
          justified.filter((name) => !failedChecks.includes(name)),
        ).toEqual([]);

        if (isExactMatch) {
          return;
        }

        // Each dimension is justified on its own. One entry covering a whole
        // document would let an unanalysed difference pass as governed merely
        // because some other difference in the same document was explained.
        const unjustified = failedChecks.filter((name) => !entry[name]);
        if (unjustified.length > 0) {
          describeDifference(keyName, unjustified, detail);
        }

        for (const name of failedChecks) {
          expect(entry[name].justification).toEqual(expect.any(String));
          expect(entry[name].justification.length).toBeGreaterThan(0);
        }
      },
      TEST_TIMEOUT_MS,
    );
  }
});
