import { IRI, OWLDataFactory, OWLOntology } from "../model/index.js";
import { OwlToRdfTranslator, rdfDataFactory } from "./index.js";

const RDF = "http://www.w3.org/1999/02/22-rdf-syntax-ns#";
const RDFS = "http://www.w3.org/2000/01/rdf-schema#";
const OWL = "http://www.w3.org/2002/07/owl#";
const EX = "https://example.com/owl-to-rdf-annotations#";

const nn = (value) => rdfDataFactory.namedNode(value);
const oneObject = (dataset, subject, predicate) => {
  const matches = [...dataset.match(subject, nn(predicate), null)];
  expect(matches).toHaveLength(1);
  return matches[0].object;
};

const ontologyFor = (factory, axiom) =>
  new OWLOntology({
    axioms: [axiom],
    ontologyID: factory.getOWLOntologyID(IRI.create(`${EX}ontology`)),
  });

describe("OwlToRdfTranslator annotated axioms", () => {
  it("recursively reifies a nested annotation on a single main triple", () => {
    const factory = new OWLDataFactory();
    const note = factory.getOWLAnnotationProperty(IRI.create(`${EX}note`));
    const nested = factory.getOWLAnnotation(
      factory.getOWLAnnotationProperty(IRI.create(`${RDFS}comment`)),
      factory.getOWLLiteral("nested"),
    );
    const outer = factory.getOWLAnnotation(
      note,
      factory.getOWLLiteral("outer"),
      [nested],
    );
    const child = factory.getOWLClass(IRI.create(`${EX}Child`));
    const parent = factory.getOWLClass(IRI.create(`${EX}Parent`));
    const dataset = new OwlToRdfTranslator().translate(
      ontologyFor(
        factory,
        factory.getOWLSubClassOfAxiom(child, parent, [outer]),
      ),
    );

    const axiomNode = [
      ...dataset.match(null, nn(`${RDF}type`), nn(`${OWL}Axiom`)),
    ][0].subject;
    expect(oneObject(dataset, axiomNode, `${OWL}annotatedSource`)).toEqual(
      nn(`${EX}Child`),
    );
    expect(oneObject(dataset, axiomNode, `${OWL}annotatedProperty`)).toEqual(
      nn(`${RDFS}subClassOf`),
    );
    expect(oneObject(dataset, axiomNode, `${OWL}annotatedTarget`)).toEqual(
      nn(`${EX}Parent`),
    );
    const outerValue = oneObject(dataset, axiomNode, `${EX}note`);

    const annotationNode = [
      ...dataset.match(null, nn(`${RDF}type`), nn(`${OWL}Annotation`)),
    ][0].subject;
    expect(
      dataset.match(annotationNode, nn(`${OWL}annotatedSource`), axiomNode)
        .size,
    ).toBe(1);
    expect(
      dataset.match(
        annotationNode,
        nn(`${OWL}annotatedProperty`),
        nn(`${EX}note`),
      ).size,
    ).toBe(1);
    expect(
      dataset.match(annotationNode, nn(`${OWL}annotatedTarget`), outerValue)
        .size,
    ).toBe(1);
    expect(
      dataset.match(
        annotationNode,
        nn(`${RDFS}comment`),
        rdfDataFactory.literal("nested"),
      ).size,
    ).toBe(1);
  });

  it("reifies every triple generated by an annotated pairwise n-ary axiom", () => {
    const factory = new OWLDataFactory();
    const annotation = factory.getOWLAnnotation(
      factory.getRDFSLabel(),
      factory.getOWLLiteral("equivalent group"),
    );
    const classes = ["A", "B", "C"].map((name) =>
      factory.getOWLClass(IRI.create(`${EX}${name}`)),
    );
    const dataset = new OwlToRdfTranslator().translate(
      ontologyFor(
        factory,
        factory.getOWLEquivalentClassesAxiom(classes, [annotation]),
      ),
    );

    expect(dataset.match(null, nn(`${OWL}equivalentClass`), null).size).toBe(2);
    const axiomNodes = [
      ...dataset.match(null, nn(`${RDF}type`), nn(`${OWL}Axiom`)),
    ].map(({ subject }) => subject);
    expect(axiomNodes).toHaveLength(2);
    for (const axiomNode of axiomNodes) {
      expect(
        dataset.match(
          axiomNode,
          nn(`${RDFS}label`),
          rdfDataFactory.literal("equivalent group"),
        ).size,
      ).toBe(1);
    }
  });

  it("preserves multiple literal, IRI, and anonymous-individual annotation values", () => {
    const factory = new OWLDataFactory();
    const target = factory.getOWLAnonymousIndividual(
      "annotation-target",
      "scope",
    );
    const annotations = [
      factory.getOWLAnnotation(
        factory.getOWLAnnotationProperty(IRI.create(`${EX}literalNote`)),
        factory.getOWLLiteral("literal value"),
      ),
      factory.getOWLAnnotation(
        factory.getOWLAnnotationProperty(IRI.create(`${EX}iriNote`)),
        IRI.create(`${EX}reference`),
      ),
      factory.getOWLAnnotation(
        factory.getOWLAnnotationProperty(IRI.create(`${EX}anonymousNote`)),
        target,
      ),
    ];
    const dataset = new OwlToRdfTranslator().translate(
      ontologyFor(
        factory,
        factory.getOWLSubClassOfAxiom(
          factory.getOWLClass(IRI.create(`${EX}Child`)),
          factory.getOWLClass(IRI.create(`${EX}Parent`)),
          annotations,
        ),
      ),
    );
    const axiomNode = [
      ...dataset.match(null, nn(`${RDF}type`), nn(`${OWL}Axiom`)),
    ][0].subject;

    expect(
      dataset.match(
        axiomNode,
        nn(`${EX}literalNote`),
        rdfDataFactory.literal("literal value"),
      ).size,
    ).toBe(1);
    expect(
      dataset.match(axiomNode, nn(`${EX}iriNote`), nn(`${EX}reference`)).size,
    ).toBe(1);
    const anonymousValue = oneObject(dataset, axiomNode, `${EX}anonymousNote`);
    expect(anonymousValue.termType).toBe("BlankNode");
  });

  it("keeps structurally distinct annotations on equal logical axioms", () => {
    const factory = new OWLDataFactory();
    const child = factory.getOWLClass(IRI.create(`${EX}Child`));
    const parent = factory.getOWLClass(IRI.create(`${EX}Parent`));
    const annotated = (label) =>
      factory.getOWLSubClassOfAxiom(child, parent, [
        factory.getOWLAnnotation(
          factory.getRDFSLabel(),
          factory.getOWLLiteral(label),
        ),
      ]);
    const ontology = new OWLOntology({
      axioms: [annotated("first"), annotated("second")],
      ontologyID: factory.getOWLOntologyID(IRI.create(`${EX}ontology`)),
    });
    const dataset = new OwlToRdfTranslator().translate(ontology);
    const axiomNodes = [
      ...dataset.match(null, nn(`${RDF}type`), nn(`${OWL}Axiom`)),
    ].map(({ subject }) => subject);

    // RDF dataset set semantics collapse the shared logical triple, while the
    // two reification nodes retain the structural annotation distinction.
    expect(
      dataset.match(
        nn(`${EX}Child`),
        nn(`${RDFS}subClassOf`),
        nn(`${EX}Parent`),
      ).size,
    ).toBe(1);
    expect(axiomNodes).toHaveLength(2);
    expect(
      axiomNodes
        .map((node) => oneObject(dataset, node, `${RDFS}label`).value)
        .sort(),
    ).toEqual(["first", "second"]);
  });

  it("attaches annotations directly to a native n-ary disjointness node", () => {
    const factory = new OWLDataFactory();
    const annotation = factory.getOWLAnnotation(
      factory.getRDFSLabel(),
      factory.getOWLLiteral("disjoint group"),
    );
    const classes = ["A", "B", "C"].map((name) =>
      factory.getOWLClass(IRI.create(`${EX}${name}`)),
    );
    const dataset = new OwlToRdfTranslator().translate(
      ontologyFor(
        factory,
        factory.getOWLDisjointClassesAxiom(classes, [annotation]),
      ),
    );

    const disjointNode = [
      ...dataset.match(null, nn(`${RDF}type`), nn(`${OWL}AllDisjointClasses`)),
    ][0].subject;
    expect(dataset.match(disjointNode, nn(`${OWL}members`), null).size).toBe(1);
    expect(
      dataset.match(
        disjointNode,
        nn(`${RDFS}label`),
        rdfDataFactory.literal("disjoint group"),
      ).size,
    ).toBe(1);
    expect(dataset.match(null, nn(`${RDF}type`), nn(`${OWL}Axiom`)).size).toBe(
      0,
    );
  });
});
