export const RDF_NAMESPACE = "http://www.w3.org/1999/02/22-rdf-syntax-ns#";
export const RDFS_NAMESPACE = "http://www.w3.org/2000/01/rdf-schema#";
export const OWL_NAMESPACE = "http://www.w3.org/2002/07/owl#";
export const XSD_NAMESPACE = "http://www.w3.org/2001/XMLSchema#";

const rdf = (name) => `${RDF_NAMESPACE}${name}`;
const rdfs = (name) => `${RDFS_NAMESPACE}${name}`;
const owl = (name) => `${OWL_NAMESPACE}${name}`;
const xsd = (name) => `${XSD_NAMESPACE}${name}`;

export const RDF_VOCABULARY = Object.freeze({
  List: rdf("List"),
  Property: rdf("Property"),
  first: rdf("first"),
  langString: rdf("langString"),
  nil: rdf("nil"),
  rest: rdf("rest"),
  type: rdf("type"),
  xmlLiteral: rdf("XMLLiteral"),
});

export const RDFS_VOCABULARY = Object.freeze({
  Class: rdfs("Class"),
  Datatype: rdfs("Datatype"),
  Literal: rdfs("Literal"),
  comment: rdfs("comment"),
  domain: rdfs("domain"),
  isDefinedBy: rdfs("isDefinedBy"),
  label: rdfs("label"),
  range: rdfs("range"),
  seeAlso: rdfs("seeAlso"),
  subClassOf: rdfs("subClassOf"),
  subPropertyOf: rdfs("subPropertyOf"),
});

export const OWL_VOCABULARY = Object.freeze({
  AllDifferent: owl("AllDifferent"),
  AllDisjointClasses: owl("AllDisjointClasses"),
  AllDisjointProperties: owl("AllDisjointProperties"),
  Annotation: owl("Annotation"),
  AnnotationProperty: owl("AnnotationProperty"),
  AsymmetricProperty: owl("AsymmetricProperty"),
  Axiom: owl("Axiom"),
  Class: owl("Class"),
  DataRange: owl("DataRange"),
  DatatypeProperty: owl("DatatypeProperty"),
  DeprecatedClass: owl("DeprecatedClass"),
  DeprecatedProperty: owl("DeprecatedProperty"),
  FunctionalProperty: owl("FunctionalProperty"),
  InverseFunctionalProperty: owl("InverseFunctionalProperty"),
  IrreflexiveProperty: owl("IrreflexiveProperty"),
  NamedIndividual: owl("NamedIndividual"),
  NegativePropertyAssertion: owl("NegativePropertyAssertion"),
  Nothing: owl("Nothing"),
  ObjectProperty: owl("ObjectProperty"),
  Ontology: owl("Ontology"),
  OntologyProperty: owl("OntologyProperty"),
  ReflexiveProperty: owl("ReflexiveProperty"),
  Restriction: owl("Restriction"),
  SymmetricProperty: owl("SymmetricProperty"),
  Thing: owl("Thing"),
  TransitiveProperty: owl("TransitiveProperty"),
  allValuesFrom: owl("allValuesFrom"),
  annotatedProperty: owl("annotatedProperty"),
  annotatedSource: owl("annotatedSource"),
  annotatedTarget: owl("annotatedTarget"),
  assertionProperty: owl("assertionProperty"),
  backwardCompatibleWith: owl("backwardCompatibleWith"),
  bottomDataProperty: owl("bottomDataProperty"),
  bottomObjectProperty: owl("bottomObjectProperty"),
  cardinality: owl("cardinality"),
  complementOf: owl("complementOf"),
  datatypeComplementOf: owl("datatypeComplementOf"),
  deprecated: owl("deprecated"),
  differentFrom: owl("differentFrom"),
  disjointUnionOf: owl("disjointUnionOf"),
  disjointWith: owl("disjointWith"),
  distinctMembers: owl("distinctMembers"),
  equivalentClass: owl("equivalentClass"),
  equivalentProperty: owl("equivalentProperty"),
  hasKey: owl("hasKey"),
  hasSelf: owl("hasSelf"),
  hasValue: owl("hasValue"),
  imports: owl("imports"),
  incompatibleWith: owl("incompatibleWith"),
  intersectionOf: owl("intersectionOf"),
  inverseOf: owl("inverseOf"),
  maxCardinality: owl("maxCardinality"),
  maxQualifiedCardinality: owl("maxQualifiedCardinality"),
  members: owl("members"),
  minCardinality: owl("minCardinality"),
  minQualifiedCardinality: owl("minQualifiedCardinality"),
  onClass: owl("onClass"),
  onDataRange: owl("onDataRange"),
  onDatatype: owl("onDatatype"),
  onProperties: owl("onProperties"),
  onProperty: owl("onProperty"),
  oneOf: owl("oneOf"),
  priorVersion: owl("priorVersion"),
  propertyChainAxiom: owl("propertyChainAxiom"),
  propertyDisjointWith: owl("propertyDisjointWith"),
  qualifiedCardinality: owl("qualifiedCardinality"),
  sameAs: owl("sameAs"),
  someValuesFrom: owl("someValuesFrom"),
  sourceIndividual: owl("sourceIndividual"),
  targetIndividual: owl("targetIndividual"),
  targetValue: owl("targetValue"),
  topDataProperty: owl("topDataProperty"),
  topObjectProperty: owl("topObjectProperty"),
  unionOf: owl("unionOf"),
  versionIRI: owl("versionIRI"),
  versionInfo: owl("versionInfo"),
  withRestrictions: owl("withRestrictions"),
});

export const XSD_VOCABULARY = Object.freeze({
  boolean: xsd("boolean"),
  integer: xsd("integer"),
  nonNegativeInteger: xsd("nonNegativeInteger"),
  string: xsd("string"),
});

export const BUILT_IN_ANNOTATION_PROPERTIES = new Set([
  RDFS_VOCABULARY.comment,
  RDFS_VOCABULARY.isDefinedBy,
  RDFS_VOCABULARY.label,
  RDFS_VOCABULARY.seeAlso,
  OWL_VOCABULARY.backwardCompatibleWith,
  OWL_VOCABULARY.deprecated,
  OWL_VOCABULARY.incompatibleWith,
  OWL_VOCABULARY.priorVersion,
  OWL_VOCABULARY.versionInfo,
]);
